version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ex_aws
    versions:
    - 2.1.6
    - 2.1.7
    - 2.1.8
    - 2.1.9
    - 2.2.0
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
    - 3.6.0
  - dependency-name: hackney
    versions:
    - 1.17.0
    - 1.17.1
    - 1.17.2
    - 1.17.3
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: mimic
    versions:
    - 1.4.0
  - dependency-name: credo
    versions:
    - 1.5.4
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
